title: Internet of Things
author: Hanzehogeschool Groningen
logo: assets/logo_iot_2.svg
copyright: "CC BY-NC-SA 4.0"
institute: Instituut voor Communicatie, Media & IT
subtitle: Workshop ESP32 microcontroller en embedded systems
subject: Een kennismaking met microcontrollers en embedded systems
description: Workshop IoT waar een client/server architectuur wordt uitgewerkt voor het meten en versturen van data.
keywords: [microcontroller, SoC, esp32, MicroPython, IoT]
exclude_patterns: ["README.md"]

latex:
  latex_engine: xelatex
  latex_documents:
    targetname: workshop.tex
html:
  home_page_in_navbar: true
  use_repository_button: false
  use_issues_button: false
  use_edit_page_button: false
  navbar_number_sections: false

sphinx:
  config:
    language: "nl"
    html_show_copyright: true
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_extra_path: ["extra"]

parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - amsmath
    - html_image
